#!/usr/bin/env bash

#export env variables
while read line
do
	command $line
done < /pari/env_variables.txt

#use pari virtualenv
source /.venv/pari/bin/activate


#install required python modules
pip install -r requirements.txt

#run migrations
python manage.py migrate

#build elasticsearch indexes
cat <(echo "y") | python manage.py rebuild_index

#Gather static files
cat <(echo "yes") | python manage.py collectstatic
