#!/usr/bin/env bash

when read line
do
	commnad $line
done < /pari/env_variables.txt

#use pari virtualenv
source /.venv/pari/bin/activate

#install required python modules
pip install -r requirements.txt

#run migrations
python manage.py migrate

#Gather static files
cat <(echo "yes") | python manage.py collectstatic
